# fly.testpinger.toml app configuration file generated for pingertest on 2023-07-12T13:45:31-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pingertest"
primary_region = "iad"

[processes]
  app = "/node -to=testponger.internal"
